name: DockerizationBackend
on:
  push:
    branches:
      - main
      
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub and deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend 
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/acedev/curatelearn_landing_page:latest
          labels: ${{ steps.meta.outputs.labels }}
          dockerfile: dockerfile  # replace with your Dockerfile's name

      # - name: Set up kubectl
      #   uses: azure/setup-kubectl@v1
      #   with:
      #     version: 'latest'

      # - name: Configure Kubernetes context
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     kubeconfig: ${{ secrets.KUBECONFIG }}

      # - name: Restart Kubernetes deployment
      #   run: |
      #     kubectl rollout restart deployment/curator-deployment -n curatelearn